---
title: "Contributions to Herbarium-based Spectral Science"
page-layout: full
---

<!-- Page-only styles -->
<style>
  .references p {
    margin-left: 2em;     /* indent the whole block */
    text-indent: -2em;    /* pull back the first line */
    line-height: 1.5;     /* nicer spacing */
  }
</style>

<div class="references">

White, D. M., F. Durgante, M. Austin, J. A. Guzmán Q., J. Kennedy, C. Nichodemus, N. Ahlstrand, C. Baraloto, B. Bektaş, K. Boughalmi, W. Cardinal-McTeague, T. L. P. Couvreur, R. Fortier, R. Fuller, O. Grace, R. Jackson, K. Karbstein, S. Kothari, A. Lee, J. Lira Viana, E. Martinez-Victoria, J. E. Meireles, T. Murphy, C. Rodriguez Vaz, D. Spalink, H. Tuomisto, C. Vasconcelos, J. Cavender-Bares. **A Protocol for Standardizing Measurements and Enabling Global Harmonization of
Herbarium Leaf Reflectance Spectra**. *EcoEvoRxiv* (2026). [https://doi.org/10.32942/X2SD4D](https://doi.org/10.32942/X2SD4D)

---

Boughalmi, K., P.G. Santacruz Endara, L.A. Bennett, M. Ecarnot, S. Bazan, D. Bastianelli, L. Bonnal, T.L.P Couvreur. **Discrimination of Annonaceae using herbarium leaf reflectance spectra under limited sample size conditions**. *bioRxiv* (2026). [https://doi.org/10.1101/2025.09.02.673631](https://doi.org/10.1101/2025.09.02.673631)

---

Cavender-Bares, J., D.M. White, N.I. Ahlstrand, M. Austin, D. Bastianelli, S. Bazan, K. Boughalmi, W. Cardinal-McTeague, E. Chacón-Madrigal, T.L.P. Couvreur, C.C. Davis, F.M. Durgante, O.M. Grace, J.A. Guzmán Q., K. Hansen, M.S. Hernández-Leal, M.J.G. Hopkins, R. Jackson, S. Kothari, A.K. Lee, É. Léveillé-Bourret, J. Pinto-Ledezma, N.L.Q. Casaverde, J.E. Meireles, B. Neto-Bradley, C.O. Nichodemus, R.H. Ree, M. Schmull, D.E. Soltis, P.S. Soltis, H. Tuomisto, S. Ustin, C.C. Vasconcelos. **Next-generation specimen digitization: capturing reflectance spectra from the world's herbaria for modeling plant biology across time, space, and taxa**. *New Phytologist* (2025). 
[https://doi.org/10.1111/nph.70645](https://doi.org/10.1111/nph.70645)

---

Neto-Bradley, B.M., P. Bonnet, H. Goëau, A. Joly, J. Cavender-Bares, D.A. Coomes. **Using reflectance spectra and Pl@ntNet to identify herbarium specimens: A case study with *Lithocarpus***. *New Phytologist* (2025).
[https://doi.org/10.1111/nph.70258](https://doi.org/10.1111/nph.70258)

---

White, D.M., J. Cavender-Bares, C.C. Davis, J.A. Guzmán Q., S. Kothari, J.M. Robles, J.E. Meireles. **Seeing herbaria in a new light: Leaf reflectance spectroscopy unlocks trait and classification modeling in plant biodiversity collections**. *New Phytologist*  (2025). 
[https://doi.org/10.1111/nph.70357](https://doi.org/10.1111/nph.70357)


</div>
