---
title: "Appendix II – Representing Tissue Conditions in Metadata for Quality Control"
include-after-body:
  text: |
    <div style="text-align:center; padding-bottom:2em;">
      CC BY 4.0 — <em>IHerbSpec Protocol</em>. 
      DOI: <a href="https://doi.org/10.5281/zenodo.15849668">10.5281/zenodo.15849668</a>
    </div>
---

This appendix provides a brief discussion and examples of the IHerbSpec approach for recording metadata pertaining to sources of biological and herborization variation that affect spectral data. As explained in [Section 6.1](part6-guidelines.qmd) Sources of Variation, we aim to capture biological variation that is scientifically meaningful, but the degraded nature of herbarium specimens requires a careful assessment and annotation of tissue quality and sources of contamination. The Tissue Metadata fields of `developmentalStage`, `hasGlue`, `hasNonGlueContamination`, `measurementFlags`, and `tissueNotes` [Table 4.3](part4-metadata.qmd#tbl-4-3) are designed to support quality control of spectral data and enable downstream filtering. 

The codes for enumerating the developmentalStage fields are provided in [Table 4.4](part4-metadata.qmd#tbl-4-4), and the codes for measurementFlags are described in [Table 4.6](part4-metadata.qmd#tbl-4-6).

Technicians should also be aware that some taxa (e.g. Myrtaceae) or tropical collections in general may naturally exhibit discoloration or non-flat, deformed surfaces (e.g., *Gasteranthus atratus*). Such characteristics do not necessarily indicate tissue degradation and poor-quality spectral data. In addition, some taxa exhibit more pronounced discoloration during herborization as a result of their biology, and such discoloration should not be interpreted as evidence of poor preservation condition. Some traits also covary; for example, young leaves wilt and become discolored faster and are more challenging to press and dry flat, so they may more often be scored as moderately or poorly preserved. 

As a reminder, **`measurementFlags` pertain only to the measurement area**, not the whole tissue unit (e.g., leaf). Since suitable measurement areas of tissues (see decision tree in [Fig. 6.1](part6-guidelines.qmd)) will not contain any contaminants, pathogens, or other damage, technicians should not be enumerating any codes in the `measurementFlags` field. This could differ in projects collecting measurements pertaining to extended uses of the specimen, e.g., symbionts, degradation, etc., that might be measuring tissue areas with these other features. 

The specimens and metadata examples in [Table A1](#tbl-a-1) have been selected to guide consistent scoring of these fields during spectral measurement and promote metadata consistency across projects. Note that the images do not specify the exact measurement area corresponding to these metadata fields (as is done in the IHerbSpec Metadata Spreadsheet for specimen NEBC_00651639 shown in main text [Fig. 2.2](part2-workflow.qmd)).

### Table A1: Select Metadata Fields and Scoring for Representative Specimens.  {#tbl-a-1}

This table provides example metadata records for herbarium specimens, illustrating how to score key fields related to tissue condition and contamination. The fields developmentalStage, hasGlue, hasNonGlueContamination, and measurementFlags refer specifically to the measurement area. Broader observations about the specimen or other tissues can be recorded in tissueNotes (see [Table 4.3](part4-metadata.qmd#tbl-4-3)). Linked specimen images are included, though they do not indicate the precise measurement area corresponding to each metadata record. This table can be downloaded on the [Protocol home page](../protocol.qmd).

### Table A1. Select Metadata Fields and Scoring for Representative Specimens {#tbl-a1}

herbariumCode_specimenID | `developmentalStage` | `hasGlue` | `hasNonGlueContamination` | `measurementFlags` | `tissueNotes`
---------- | ---------- | ---------- | ---------- | ---------- | ----------
[A_00631088](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=794136) | `mature` | `TRUE` | `FALSE` | `MediumPreservation` | discolored
[A_00672503](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=834226) | `mature` | `FALSE` | `TRUE` | `GoodPreservation`|PathogenPresent|FungusPresent | Small necrotic spots in measurement area
[A_00746288](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=800877) | `mature` | `TRUE` | `FALSE` | `MediumPreservation` | Discolored. Glue on loose leaf in measurement area.
[A_00772865](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=793672) | `young` | `FALSE` | `FALSE` | `PoorPreservation` | Measured leaves uneven, mottled, discolored, breakage
[A_2613405](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=1895126) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | 
[A_2614928](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=1915798) | `mature` | `uncertain` | `TRUE` | `PoorPreservation`|OrganismPresent|FungusPresent|MoldPresent | Discolored, herbivory on sheet. Glue used on sheet but unsure if in measurement area.
[AAU_A.S.Barfod48062](https://www.aubot.dk/show_entry.php?CatalogNumber=A.S.Barfod48062&&sp_set=all&identification=Danaea%20wendlandii) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|MidveinPresent|DebrisPresent|Herbivory | Herbivory on specimen
[AAU_I.A.Chacon1199](https://www.aubot.dk/show_entry.php?CatalogNumber=I.A.Chacon1199&&sp_set=all&identification=Danaea%20nodosa) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|AlcoholPresent | discolored, grayish spots on specimen
[AAU_R.C.Moran6023](https://www.aubot.dk/show_entry.php?CatalogNumber=R.C.Moran6023&&sp_set=img&identification=Danaea) | `mature` | `FALSE` | `TRUE` | `GoodPreservation`|AlcoholPresent | 
[ALF_035514](https://recolnat.fr/fr/specimens/551558e3-8292-4c78-8af6-1ca695e2d7c1?fromExplore=`TRUE`) | `mature`, `young` | `FALSE` | `FALSE` | `GoodPreservation` | 
[ECON_00338371](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=231791) | `young` | `FALSE` | `FALSE` | `MediumPreservation` | Discolored, wrinkled. Specimen burnt but not in target area.
[GH_00611866](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=395867) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | Discolored specimen
[INPA_142198](https://drive.google.com/file/d/1Jq1xf6qXY9WzqT3HxjgrvNLRF8hPr3QU/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | discolored, herbivory on specimen
[INPA_179322](https://drive.google.com/file/d/1FNv9fwFMu_FowDtoXSLP4lA5cIDgNI4u/view) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[INPA_184434](https://drive.google.com/file/d/14IQvmZxq2vicLC2M7QoNsNZvEsNO_xse/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | Herbivory on specimen, necrotic leaf
[INPA_187932](https://drive.google.com/file/d/1BE6PCBDtpcImSD5t_suGDkKaDA6fZVWf/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | burnt leaves on specimen
[INPA_203125](https://drive.google.com/file/d/1KoDRZW9sM49NMMON1UMbV33MX3ygsWaE/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | discolored, wrinkled leaves
[INPA_218399](https://drive.google.com/file/d/1S-P4yb8-2nb6taY44eR0sXkO_ImGxr9C/view) | `mature` | `TRUE` | `FALSE` | `PoorPreservation` | discolored, herbivory, wrinkled and burnt leaves
[INPA_264413](https://drive.google.com/file/d/1xg7fWYeZ_6q-w4WmGzdwfVSiulkIYHtx/view) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[INPA_267597](https://drive.google.com/file/d/1vHpKxEW1N3xl0rEa1RJysfvGJWubZ5Am/view) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[INPA_275373](https://drive.google.com/file/d/1LQQ5cEbOpzctYiUI94GzqUZEu3NJPN6m/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | discolored, mold, grayish spots on older leaves specimen
[INPA_278882](https://drive.google.com/file/d/1bc4Ye52pVqNwoEuDBFukMT4rVbzuC93n/view) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|AlcoholPresent | discolored
[INPA_4628](https://drive.google.com/file/d/1l5lxkfJ9gvhXsE34NnzWiwpqpif4RCxD/view) | `mature` | `FALSE` | `TRUE` | `PoorPreservation`|PreservativePresent | mold, whitish powder (diatoms?), poor storage conditions
[INPA_59178](https://drive.google.com/file/d/1V6tDj3iPp0qSokmGIe_tf-g2FJcUll2Z/view) | `mature` | `TRUE` | `TRUE` | `PoorPreservation`|PathogenPresent|OrganismPresent | discolored, herbivory, dark spots on leaves
[INPA_72939](https://drive.google.com/file/d/1dx2xVCjb6YVd23KBwfPNRK9-R9k7qw2p/view) | `mature` | `TRUE` | `TRUE` | `PoorPreservation`|FungusPresent | discolored, herbivory on measured leaves
[INPA_97794](https://drive.google.com/file/d/1JJeU30mNRJtNqQqWCwi72y5O2A8f9ds2/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | wrinkled leaves
[INPA264208](https://drive.google.com/file/d/1nF5EyZaAEE1VVB2tsZxCX6QsyQwqdgTJ/view) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | Measurement area not flat. Herbivory on sheet
[M_PU681750](https://recolnat.fr/fr/specimens/a64758d3-7cc2-4032-b54b-280ba3dc91ef?fromExplore=`TRUE`) | `mature` | `FALSE` | `uncertain` | `MediumPreservation` | Discolored; Alcohol preservation suspected.
[MIN_332436](https://bellatlas.umn.edu/collections/individual/index.php?occid=3069677&clid=0) | `mature` | `FALSE` | `FALSE` | `MediumPreservation`|MidveinPresent | wrinkled leaves
[MIN_370477](https://bellatlas.umn.edu/collections/individual/index.php?occid=3069026&clid=0) | `mature` | `FALSE` | `FALSE` | `PoorPreservation` | discolored, wrinkled leaves
[MIN_588200](https://bellatlas.umn.edu/collections/individual/index.php?occid=3069134&clid=0) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NEBC_00634726](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=613103) | `young` | `FALSE` | `FALSE` | `PoorPreservation` | Measurement area leaves uneven, discolored
[NEBC_00636882](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=613000) | `uncertain` | `FALSE` | `TRUE` | `PoorPreservation`|PathogenPresent | Senescent? Uneven, blight, necrosis in measurement. But no glue.
[NEBC_00651639](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=585980) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NEBC_00677096](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=793836) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|PathogenPresent|FungusPresent | Leaves on sheet wrinkled and deformed
[NEBC_00695035](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=800585) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NEBC_00746092](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=800514) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|PathogenPresent | discolored
[NEBC_00898559](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=800514) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NEBC_02618198](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=1704329) | `mature` | `FALSE` | `FALSE` | `MediumPreservation` | Dark spots on measured leaf
[NEBC_02618743](https://kiki.huh.harvard.edu/databases/specimen_search.php?mode=details&id=1739124) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NY_00042623](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=355043) | `mature` | `TRUE` | `FALSE` | `GoodPreservation` | 
[NY_00043385](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=716096) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|PathogenPresent | Discolored; dark spots on leaves
[NY_00194824](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=433163) | `mature` | `FALSE` | `FALSE` | `GoodPreservation` | 
[NY_00402473](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=648358) | `mature` | `TRUE` | `FALSE` | `MediumPreservation`|MoldPresent | Discolored; dark spots on leaves
[NY_00709210](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=602603) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|PathogenPresent | Discolored; herbivory on specimen. Alcohol suspected.
[NY_01163859](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=1392604) | `mature` | `TRUE` | `FALSE` | `MediumPreservation` | Discolored; herbivory on specimen
[NY_02498899](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=2719809) | `mature` | `TRUE` | `FALSE` | `MediumPreservation` | Discolored 
[NY_02499746](https://sweetgum.nybg.org/science/vh/specimen-details/?irn=2720050) | `mature` | `FALSE` | `TRUE` | `PoorPreservation`|MoldPresent | Dark spots on leaves; Discolored
[P_00391795](https://science.mnhn.fr/institution/mnhn/collection/p/item/p00391795) | `mature` | `FALSE` | `uncertain` | `MediumPreservation` | wrinkled leaves; possible chemical preservative.
[P_05198525](https://recolnat.fr/fr/specimens/963508d0-6708-40ac-a2a2-17854b64a1f8?fromExplore=`TRUE`) | `mature` | `FALSE` | `TRUE` | `PoorPreservation`|FungusPresent | Herbivory on sheet. 
[P_05198660](https://recolnat.fr/fr/specimens/7a679ebb-c03a-4842-ae7c-d3ed7a932e05?fromExplore=`TRUE`) | `mature` | `FALSE` | `TRUE` | `MediumPreservation`|AlcoholPresent | discolored. 

---

# Navigate the protocol
Browse additional parts and appendices below

- [**Part 1**](part1-overview.qmd) – Overview  
- [**Part 2**](part2-workflow.qmd) – Measurement and Metadata Workflow  
- [**Part 3**](part3-filenames.qmd) – Filename Conventions and Formats  
- [**Part 4**](part4-metadata.qmd) – Metadata and Databasing  
- [**Part 5**](part5-instrumentation.qmd) – Instrumentation and Materials Guidelines  
- [**Part 6**](part6-guidelines.qmd) – Selecting Tissues for Spectral Measurement  
- [**References**](references.qmd)
- [**Appendix I**](appendix1.qmd) – Number of Measurements per Tissue  
- [**Appendix II**](appendix2.qmd) – Tissue Metadata for Quality Control  
